// src/app/experience/experience.component.ts
import { Component } from '@angular/core';
import { NgbNavModule } from '@ng-bootstrap/ng-bootstrap';
import { getAllExperiences } from 'src/assets/experiences';

@Component({
    selector: 'app-experience',
    templateUrl: './experience.component.html',
    styleUrls: ['./experience.component.css'],
})
export class ExperienceComponent {
    experiences = getAllExperiences()
        .filter((e) => e.featured)
        .sort((a, b) => Number(a.time > b.time) - Number(b.time > a.time))
        .reverse();
    active = this.experiences[0]._id.toString();

    parseDescription(desc: string) {
        return desc;
    }
}

<div id="experience-div">
    <div id="experience-inner-div">
        <h1 class="w-100 text-c1 p-2">Experience</h1>

        <div class="d-flex p-2 pt-4">
            <div ngbNav #nav="ngbNav" [(activeId)]="active" class="nav-pills flex-column w-25" orientation="vertical">
                <ng-container *ngFor="let e of this.experiences" ngbNavItem={{e._id}}>
                    <button ngbNavLink>{{e.position}}</button>
                    <ng-template ngbNavContent>
                        <p class="experience-position-company-time text-light">{{e.formattedTime}} @ {{e.company}}</p>
                        <ul class="experience-position-description text-light">
                            <li *ngFor="let d of e.description">{{parseDescription(d)}}</li>
                        </ul>
                        <p class="text-light experience-position-skills">Skills: {{e.skills.join(', ')}}</p>
                    </ng-template>
                </ng-container>
            </div>
        
            <div [ngbNavOutlet]="nav" class="ms-4 w-75"></div>
        </div>


    </div>
</div>

// react-portfolio/src/components/Experience.tsx
import React, { useState } from 'react';
import { getAllExperiences } from '../assets/experiences';
import './Experience.css';

const Experience: React.FC = () => {
  const experiences = getAllExperiences()
    .filter((e) => e.featured)
    .sort((a, b) => Number(a.time > b.time) - Number(b.time > a.time))
    .reverse();

  const [activeId, setActiveId] = useState<string>(experiences[0]._id.toString());

  const parseDescription = (desc: string) => {
    return desc;
  };

  const activeExperience = experiences.find(e => e._id.toString() === activeId);

  return (
    <div id="experience-div">
      <div id="experience-inner-div">
        <h1 className="w-100 text-c1 p-2">Experience</h1>

        <div className="d-flex p-2 pt-4">
          <div className="nav-pills flex-column w-25" style={{ display: 'flex', flexDirection: 'column' }}>
            {experiences.map((experience) => (
              <button
                key={experience._id}
                className={`nav-link ${activeId === experience._id.toString() ? 'active' : ''}`}
                onClick={() => setActiveId(experience._id.toString())}
              >
                {experience.position}
              </button>
            ))}
          </div>

          <div className="ms-4 w-75">
            {activeExperience && (
              <div>
                <p className="experience-position-company-time text-light">
                  {activeExperience.formattedTime} @ {activeExperience.company}
                </p>
                <ul className="experience-position-description text-light">
                  {activeExperience.description.map((desc, index) => (
                    <li key={index}>{parseDescription(desc)}</li>
                  ))}
                </ul>
                <p className="text-light experience-position-skills">
                  Skills: {activeExperience.skills.join(', ')}
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Experience;
