// react-portfolio/src/components/Toc.tsx
import React from 'react';
import './Toc.css';

const Toc: React.FC = () => {
  const sections = [
    { name: 'Skills', divID: 'skills-div' },
    { name: 'Experience', divID: 'experience-div' },
    { name: 'Projects', divID: 'projects-div' },
  ];

  const scrollTo = (elementId: string) => {
    if (elementId.startsWith('#')) {
      elementId = elementId.substring(1);
    }

    const el = document.getElementById(elementId);
    if (el) {
      console.log('Scrolling to table of contents');
      el.scrollIntoView();
    } else {
      console.log(`Cannot scroll to non-existing element #${elementId}`);
    }
  };

  return (
    <div id="toc-div" className="w-100 flex-column d-flex align-items-end">
      <div id="toc-inner-div" className="flex-column d-flex align-items-end">
        {sections.map((section, index) => (
          <div
            key={index}
            className="toc-item-div text-c1 d-flex"
          >
            <p
              className="toc-item cursor-clickable fira-code"
              onClick={() => scrollTo(section.divID)}
            >
              {section.name}
            </p>
            &nbsp; &lt;
          </div>
        ))}
      </div>
    </div>
  );
};

export default Toc;

// angular-old/src/app/toc/toc.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-toc',
    templateUrl: './toc.component.html',
    styleUrls: ['./toc.component.css'],
})
export class TocComponent {
    sections = [
        {name: 'Skills', divID: 'skills-div'},
        {name: 'Experience', divID: 'experience-div'},
        {name: 'Projects', divID: 'projects-div'},
    ];

    constructor() {
        return;
    }

    public scrollTo(elementId: string) {
        if (elementId.startsWith('#')) {
            elementId = elementId.substring(1);
        }

        let el = document.getElementById(elementId);
        if (el != undefined && el != null) {
            console.log('Scrolling to table of contents');
            el.scrollIntoView();
        } else {
            console.log('Cannot scroll to non-existing element #' + elementId);
        }
    }
}

<div id="toc-div" class="w-100 flex-column d-flex align-items-end">
    <div id="toc-inner-div" class="flex-column d-flex align-items-end">
        <div
            *ngFor="let s of this.sections"
            class="toc-item-div text-c1 d-flex"
        >
            <p class="toc-item cursor-clickable fira-code" (click)="this.scrollTo(s.divID)">
                {{ s.name }}
            </p>
            &nbsp; &lt;
        </div>
        <!-- <div class="toc-item-div text-c1 d-flex">
        <p class="toc-item ">Section 2</p>
        &nbsp; &lt;
    </div>
    <div class="toc-item-div text-c1 d-flex">
        <p class="toc-item ">Section 3</p>
        &nbsp; &lt;
    </div> -->
    </div>
</div>
