// src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import * as $ from 'jquery';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
    title = 'portfolio';

    ngOnInit() {
        console.log(50);
        $(window).on('load resize scroll', function () {
            $('#bg-static').each(function () {
                var mainHeight = $('#main').height() || 0;

                var windowTop = $(window).scrollTop();
                var elementTop = $(this).offset()?.top;
                if (elementTop == undefined || windowTop == undefined) {
                    elementTop = 0;
                    windowTop = 0;
                }
                var topdiff = sigmoid(windowTop - elementTop, mainHeight / 10);

                var leftPosition = Math.max(70 - (70 - 0) * topdiff, 0);
                var topPosition = Math.min(62 + (100 - 62) * topdiff, 100);

                $(this)
                    .find('#bg-dynamic')
                    .css({
                        backgroundPositionX: leftPosition.toString() + '%',
                        backgroundPositionY: topPosition.toString() + '%',
                    });
            });
        });
        console.log($('#main').width());
    }
}

function sigmoid(x: number, k: number) {
    return 2 * (1.0 / (1.0 + Math.exp(-x / k)) - 0.5);
}

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<div id="bg-static">
    <div id="bg-dynamic">
    </div>
    <div id="main">
        <app-title />
    </div>
    
</div>

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content above * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * End of Placeholder * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<router-outlet></router-outlet>

// react-portfolio/src/App.tsx
import React, { useEffect } from "react";
import "./App.css";
import "./common.css";
import Title from "./components/Title";
import Toc from "./components/Toc";
import Skills from "./components/Skills";
import Experience from "./components/Experience";
import Projects from "./components/Projects";
import Footer from "./components/Footer";

const App: React.FC = () => {
    useEffect(() => {
        const handleScroll = () => {
            const bgStatic = document.getElementById("bg-static");
            const main = document.getElementById("main");
            const bgDynamic = document.getElementById("bg-dynamic");

            if (bgStatic && main && bgDynamic) {
                const mainHeight = main.offsetHeight || 0;
                const windowTop = window.scrollY;
                const elementTop = bgStatic.offsetTop || 0;
                const topDiff = sigmoid(
                    windowTop - elementTop,
                    mainHeight / 10,
                );

                const leftPosition = Math.max(70 - (70 - 0) * topDiff, 0);
                const topPosition = Math.min(62 + (100 - 62) * topDiff, 100);

                bgDynamic.style.backgroundPositionX = `${leftPosition}%`;
                bgDynamic.style.backgroundPositionY = `${topPosition}%`;
            }
        };

        window.addEventListener("load", handleScroll);
        window.addEventListener("resize", handleScroll);
        window.addEventListener("scroll", handleScroll);

        return () => {
            window.removeEventListener("load", handleScroll);
            window.removeEventListener("resize", handleScroll);
            window.removeEventListener("scroll", handleScroll);
        };
    }, []);

    const sigmoid = (x: number, k: number): number => {
        return 2 * (1.0 / (1.0 + Math.exp(-x / k)) - 0.5);
    };

    return (
        <div id="bg-static">
            <div id="bg-dynamic"></div>
            <div id="main">
                <Title />
                <Toc />
                <Skills />
                <Experience />
                <Projects />
                <Footer />
            </div>
        </div>
    );
};

export default App;
